### ISSUE TITLE
Create account

### ISSUE THREAD

**Issue by akiikr513** [akiikr513/training_2021#2]
ask Govinda and Akash to create account in git, and install required software

**Comment by akiikr513** [comment]
texted Them , waiting for Reply

**Comment by akiikr513** [comment]
https://github.com/govinda15 govinda

**Comment by govinda15** [comment]
hi

**Comment by akiikr513** [comment]
asked Akash M to join , waiting for reply

**Comment by akiikr513** [comment]
akash m has joined , 
waiting for request approval

**Comment by akiikr513** [comment]
@akashmanavarthe  hi , wellcome

**Comment by akiikr513** [comment]
this is all for this task,
closing now
